### ISSUE TITLE
[DSP] Implement support for Single Pass acquisition

### ISSUE THREAD

**Issue by jvff** [lnls-dig/halcs#128]
# Single Pass Acquisition

Should allow reading a sample window when a data threshold is reached. The values in the window is used to calculate the bunch position using a simple RMS calculation.

## Implementation

Implement the feature in `libhalcs_client`. The following functions should be available:

- `halcs_client_get_rms_x()` and `halcs_client_get_rms_y()`: reads the sample window from the latest acquisition for every BPM channel and returns the calculated position;

Update the EPICS IOC:

- Export a PV for the single pass X and Y values
- Export a PV for the BPM Mode (Single pass or multi-bunch)
- Update the acquisition code to handle the single pass mode by updating the single pass X and Y values

**Comment by lerwys** [comment]
Done a long time ago
